name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/my-ai-app .

    - name: Push Docker Image
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/my-ai-app

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy my-ai-app \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/my-ai-app \
          --platform managed \
          --region asia-south1 \
          --allow-unauthenticated
          --set-env-vars GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}